### ISSUE TITLE
search doesn't find sets or decks by code

### ISSUE THREAD

**Issue by tooomm** [mtgjson/mtgjson-website#181]
It only shows the related mention in the changelog.

**Comment by staghouse** [comment]
Merged via #184, however will require monitoring after deployment as the change is not immediate (SEO spider crawling is required)

**Comment by tooomm** [comment]
The search still doesn't find a result for e.g. `akh`.

**Comment by staghouse** [comment]
Trying another implementation that is closer to what Algolia expect data to look like. Via #195

**Comment by tooomm** [comment]
I think the idea of the `awaiting build` and `awaiting spider` labels are to not close the issues until a new site is build/deployed and the new feature tested.

**Comment by ZeldaZach** [comment]
I deployed last night... which is why I closed

**Comment by tooomm** [comment]
The search just still doesn't show any results for `akh` for example...

**Comment by staghouse** [comment]
Agree with tooom on this one for this specific ticket. Spiders take a few days to recrawl.

**Comment by tooomm** [comment]
Still nothing. Are you sure it's normal to take so much time for the crawl?

**Comment by staghouse** [comment]
Confirmed spiders still not crawling. Will continue work.

**Comment by staghouse** [comment]
This is not going to happen as the Algolia search isnt that intelligent no matter how hard i want it to be. If its that big of a deal we can look at further Search options in the future but this is stale now.
