### ISSUE TITLE
Links break going to SOMEPATH/var/www/public_html/SOMEPATH

### ISSUE THREAD

**Issue by thecravenone** [mtgjson/mtgjson-website#397]
Summary: Some links break, taking you to SOMEPATH/var/www/public_html/SOMEPATH . I have only reproduced this for opening in new tabs.

### Steps to reproduce

1. Go to https://mtgjson.com/
2. In the left sidebar, under Documentation, open **AllCards** in a new tab (middle click or right-click->open in new tab)

### What is expected?

New tab will be open to https://mtgjson.com/files/all-cards/

### What is actually happening?

New tab is open to https://mtgjson.com/var/www/mtgjson.com/public_html/files/all-cards

### Other relevant information

I've also encountered this when using the back button, but I was unable to determine what steps I took to reproduce that.

Video showing an example of a link working, both in the same tab and a new tab followed by an example of a link working in the same tab but not in a new tab: https://files.seemsgood.net/mtg_json_bug-2020-03-01.mp4

**Comment by ZeldaZach** [comment]
Fixed already

**Comment by jroed** [comment]
This is still occurring for me and is reproducible by following the above mentioned steps. I'm using Firefox 75.0 (64-bit).

**Comment by staghouse** [comment]
For clarity let me explain what is going on as people might not realize why this seems intermittent.

Originally we had the download files at a download path of `/json` while simultaneously creating a documentation route for `/files` - this was intended and caused no concern at the time. Later, we decided to change the path of `/json` to `/files` for downloads and symlinked `/json` to still work with `/files`. At this time on local development this did not cause any issues as the resources were remotely fetched and the local environment is not a direct clone of the remote server.

The problem is this: `/files` is both a server directory for json assets and a Vue router directory for documentation. If the Vue router is not successfully loaded entirely then the site will throw an error. As well, the server itself will try to match the pathing to its desired resources and ultimately both logics will fail in a beautiful disaster that we are seeing.

V5 of the documentation will resolve this entirely with other means of change however for V4 the following will happen:

The url path of `/files/*` for documentation will become `/file/*` and `/files` for assets will be untouched, leaving both URI paths to their own accord.

Visually nothing should change other than the URL addresses for documentation of files.
